spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}

custom-config:
  google:
    redirect-uri: http://localhost:4200

payu:
  client-id: ${PAYU_CLIENT_ID}
  client-secret: ${PAYU_CLIENT_SECRET}
  merchant-pos-id: ${PAYU_MERCHANT_POS_ID}
  shop-id: ${PAYU_SHOP_ID}
  notify-url: ${PAYU_NOTIFY_URL}
  continue-url: ${PAYU_CONTINUE_URL}
  language: pl